/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  shockRoot: [
    'about',
    'terms/terms',
    'contact',
    'press',
  ],
  wallet: [
    'wallet/intro',
    'wallet/add-node',
    'wallet/faq',
  ],
  lnpub: [
    {type: 'doc', id: 'pub/intro', label: 'Intro'},
    'pub/configuration',
    'pub/watchdog',
    'pub/faq',
    'pub/docker',
    'pub/start9',
    'pub/umbrel',
    ],
  video: [
    'video/intro',
    'video/publish',
    ],
  sanctum: [
    'sanctum/intro',
    'sanctum/remote',
    ],
   };

export default sidebars;
